extends SceneTree
const Progress = preload("res://src/discipline_progress.gd")
const Profiles = preload("res://src/discipline_profiles.gd")
const Skills = preload("res://prototypes/sparring_arena/lineage_skills.gd")
const Encounter = preload("res://prototypes/training_clearing/encounter.gd")

func _initialize() -> void: _run.call_deferred()

func _run() -> void:
	var progress := Progress.new()
	assert(progress.total_level() == 12 and progress.overall_level() == 1)
	assert(Progress.threshold(2) == 100 and Progress.threshold(3) == 350)
	progress.award("attack",99)
	assert(progress.level("attack") == 1)
	progress.award("attack",1)
	assert(progress.level("attack") == 2)
	progress.award("attack",-100)
	assert(progress.xp.attack == 100)
	progress.award("attack",99999999)
	assert(progress.level("attack") == 99 and progress.xp.attack == Progress.threshold(99))
	var copy := Progress.new()
	copy.restore(progress.snapshot())
	assert(copy.snapshot() == progress.snapshot())
	copy.award("focus",100)
	assert(progress.level("focus") == 1)
	var model := Encounter.new()
	model.progression = Progress.new()
	model.inventory.configure("human",CharacterCatalog.reference_loadout("human"))
	assert(not model.begin_lineage_skill(1) and model.mana == 100)
	assert(model.lineage_cooldowns[1] == 0)
	assert(model.begin_lineage_skill(0))
	model.step(.9,0,false)
	assert(model.progression.xp.attack == 0,"Whiffs must not train Attack")
	model._damage_enemy(model.enemies[0],false)
	assert(model.progression.xp.attack == 40 and model.progression.xp.strength == 20)
	model._damage_enemy(model.enemies[0],false)
	model._damage_enemy(model.enemies[0],false)
	assert(model.progression.xp.attack == 100,"XP is capped by actual remaining HP")
	model._damage_enemy(model.enemies[0],false)
	assert(model.progression.xp.attack == 100,"Dead targets cannot grant XP")
	model.progression.award("strength",50)
	assert(model.progression.allows(Skills.common_skills()[0]))
	model.attack_time = 0
	assert(model.begin_lineage_skill(4),"Discipline skill activates once both requirements are met")
	for lineage in CharacterCatalog.race_ids():
		var kit := Skills.kit(lineage)
		assert(kit.size() == 4)
		for skill in kit: assert(skill.lineage == lineage and skill.has("requirements"))
	var before: int = model.progression.xp.exploration
	model.progression.explore(Vector2(500,480),false,0)
	model.progression.explore(Vector2(500,480),false,0)
	assert(model.progression.xp.exploration == before+25)
	var scene = load("res://prototypes/training_clearing/training_clearing.tscn").instantiate()
	root.add_child(scene)
	scene.set_physics_process(false)
	scene.model.progression.award("attack",100)
	scene.model.progression.award("strength",100)
	scene._update_view(0)
	assert(not scene.skill_buttons[4].locked and scene.skill_buttons[5].locked)
	var saved_progress = scene.model.progression
	scene._restart()
	assert(scene.model.progression == saved_progress and saved_progress.level("attack") == 2)
	scene._toggle_inventory()
	scene.inventory_panel.disciplines_requested.emit()
	assert(scene.paused and scene.skill_overview.discipline_panel.visible)
	assert(scene.skill_overview.discipline_panel.rows.size() == 12)
	scene.skill_overview.discipline_panel.show_skill(4)
	assert("Shared discipline skill" in scene.skill_overview.discipline_panel.detail.text)
	scene._toggle_skills()
	assert(not scene.paused)
	scene.free()
	assert(Profiles.get_profile(self,"human").level("attack") == 2)
	assert(Profiles.get_profile(self,"goblin").level("attack") == 1)
	print("PASS: discipline curve/cap, outcome XP, unlock enforcement, shared/lineage skills, profile isolation, restart and menu flow")
	quit()
