"""Offline review document, readable without a build server or external assets."""
from build import *
import json

def main():
 data=json.loads((OUT/'manifest.json').read_text());maps=data['maps']
 names={'open_lands':'Humans / Open Lands','tidekin_sea':'Tidekin Sea'}
 top=''
 for ov in data['overviews']:
  title=names[ov['region']]+(' — hometown' if ov['type']=='hometown' else ' — entire region')
  top+=f'<a class="overview" href="{ov["file"]}"><img src="{ov["file"]}" alt="{ESC(title)}"><span>{ESC(title)}</span></a>'
 cards=''
 for d in maps:
  src=f'{d["region"]}/{d["id"]}.svg'
  cards+=f'''<article data-region="{d['region']}" data-group="{d['group']}" data-query="{ESC((d['name']+' '+d['landmark']+' '+d['id']+' '+d['story']).lower())}"><a href="{src}" target="_blank"><img loading="lazy" src="{src}" alt="{ESC(d['name']+' — '+d['landmark'])}"></a><div class="copy"><small>{names[d['region']]} · {d['group']} {'· planned outdoor map' if d['planned_only'] else ''}</small><h2><a href="{src}" target="_blank">{ESC(d['name'])}</a></h2><p>{ESC(d['story'])}</p><a class="download" href="{src}" download>Download SVG ↗</a></div></article>'''
 html_=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Human & Tidekin — complete map design atlas</title>
<style>*{{box-sizing:border-box}}body{{margin:0;background:#f7f1e4;color:#223e43;font:17px/1.55 system-ui,sans-serif}}header,main,footer{{max-width:1680px;margin:auto;padding:40px}}.eyebrow,small{{color:#4b787c}}.eyebrow{{letter-spacing:.2em;font-size:13px;text-transform:uppercase}}h1{{font:clamp(36px,5vw,70px)/1.07 Georgia,serif;max-width:1080px;margin:16px 0 25px}}header p{{max-width:900px}}.overview-grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}}.overview{{background:#e5ede7;padding:12px;border:1px solid #abc0b5;border-radius:12px;color:inherit;text-decoration:none}}.overview img{{width:100%;height:240px;object-fit:contain}}.overview span{{display:block;font-size:15px;font-weight:650;padding:8px}}.filters{{position:sticky;top:0;z-index:2;background:#f7f1e4f5;backdrop-filter:blur(10px);display:flex;gap:12px;flex-wrap:wrap;align-items:center;padding:18px 0;border-bottom:1px solid #c1cfc5}}input,select{{font:inherit;padding:10px 14px;border:1px solid #95aaa1;background:white;border-radius:6px;color:inherit}}input{{flex:1;min-width:240px}}.grid{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;margin-top:28px}}article{{background:#fffaf0;border:1px solid #ccd4c8;border-radius:12px;overflow:hidden}}article img{{display:block;width:100%;height:520px;object-fit:contain;background:#f2ebdc}}.copy{{padding:20px 25px}}h2{{font:29px/1.2 Georgia,serif;margin:10px 0}}a{{color:inherit}}h2 a{{text-decoration:none}}.copy p{{font-size:15px;color:#52645e}}.download{{font-size:14px;color:#326a71}}[hidden]{{display:none!important}}footer{{font-size:14px;border-top:1px solid #b7c7bb}}code{{font-size:12px}}@media(max-width:800px){{header,main,footer{{padding:24px}}.overview-grid,.grid{{grid-template-columns:1fr}}.overview img{{height:300px}}}}</style>
<header><div class="eyebrow">Lineage Forge · September 2026 · editable vector layouts</div><h1>Places to climb.<br>Places to live.</h1><p><strong>80 individual maps, four illustrated overviews.</strong> Every Human and Tidekin map in the hometown and regional design records, with platforms, stairs, ladders, ropes, furniture, destinations and residents. These are new level-design proposals; game geometry is unchanged.</p><div class="overview-grid">{top}</div></header>
<main><div class="filters"><input id="search" type="search" aria-label="Search maps" placeholder="Search a map, landmark or route…"><select id="region" aria-label="Region"><option value="">Both regions</option><option value="open_lands">Humans / Open Lands · 41</option><option value="tidekin_sea">Tidekin Sea · 39</option></select><select id="group" aria-label="Map group"><option value="">All maps</option><option value="village">Village</option><option value="stronghold">Stronghold</option><option value="story">Story site</option><option value="wilds">Wilds / progression</option></select><span id="count" aria-live="polite">80 maps</span></div><div class="grid">{cards}</div></main>
<footer><p>Sources: DESIGN-0014 Home-town maps; DESIGN-0022 Detailed world map and monster-level plan; DESIGN-0023 Tidekin Sea; current NPC rosters. The 22 proposed Human outdoor maps are included alongside the existing 19-map atlas. Open an SVG to zoom without losing detail or edit it in a vector editor.</p><p><a href="README.md">Reading guide and complete index</a> · <a href="manifest.json">Structured map inventory</a> · SVGs contain native paths and text, without embedded raster paintings or external dependencies.</p></footer>
<script>const cards=[...document.querySelectorAll('article')];function filter(){{const q=document.getElementById('search').value.toLowerCase(),r=document.getElementById('region').value,g=document.getElementById('group').value;let n=0;for(const c of cards){{c.hidden=!!((q&&!c.dataset.query.includes(q))||(r&&c.dataset.region!==r)||(g&&c.dataset.group!==g));if(!c.hidden)n++;}}document.getElementById('count').textContent=n+' maps';}}for(const id of ['search','region','group'])document.getElementById(id).addEventListener('input',filter);</script></html>'''
 (OUT/'index.html').write_text(html_)
 md=['# Human & Tidekin map design atlas','', '**80 detailed side-scroll SVGs + 4 illustrated overview SVGs.**','', '[Open the offline visual catalogue](index.html). Each file is a standalone, editable SVG with native paths, text and reusable vector symbols. These are authored design proposals, not changes to game collision or scenery.','', '## Overview maps','']
 for ov in data['overviews']:md.append(f'- [{names[ov["region"]]} — {ov["type"]}]({ov["file"]})')
 md+=['','## How to read a detail sheet','','- Map canvases follow traversal: Tower Base is 1400 × 2800, Winding Stair 1400 × 3500, and the Solar 1600 × 2400. Their enclosed interiors climb from a lower entrance to upper landings. Open each SVG to inspect at full size.','- Pale platform edges and furniture tops are landing surfaces. Timber galleries, roofwalks, root shelves and stone terraces use distinct structural materials.','- All main raised landings connect to the public floor through an explicit stair, ladder or rope. Furniture supplies additional optional hops. Layout coordinates are design-sheet units; final game jump spacing still needs implementation playtesting.','- Golden `P1…` exits map exactly to the destination list. `R` marks local recovery. Numbered small characters map to named residents in the footer.','- The first footer explains the place’s spatial story; the second names destinations and inhabitants. Stronghold and story access rules remain intact.','- Soft, low-contrast background forms support detailed foreground routes. This atlas develops MapleStory-like layered side-scrolling traversal using this project’s own Human and Tidekin architecture.','','## Tidekin art direction','','[Moodboard comparison and map-by-map review](TIDEKIN-REVIEW.md). Tidewharf uses piled docks and coral awnings, the Pearl Citadel uses open shell pavilions and cascading sluices, and the Sunken Shrine uses submerged coral ruins. Outdoor maps retain their own reef, mangrove, nursery, storm and ancient-water identities.','','## Coverage','','The scope is the union of the existing atlas and the full DESIGN-0022 regional plan: **41 Human/Open Lands maps** (15 hometown, four training/wilderness, 22 planned outdoor maps) and **39 Tidekin maps** (17 hometown and 22 outdoor maps). The narrower runtime atlas alone would omit the planned Human maps.','','Sources: [hometowns](../../docs/game/0014-hometown-maps.md), [world level plan](../../docs/game/0022-world-map-level-plan.md), [Tidekin regional description](../../docs/game/0023-tidekin-sea-region.md). NPC names follow the current hometown rosters.','','## All maps','']
 for region in names:
  md += ['### '+names[region],'','| Map | Group | Landmark / spatial hook |','| --- | --- | --- |']
  for d in maps:
   if d['region']==region:md.append(f'| [{d["name"]}]({region}/{d["id"]}.svg) | {d["group"]} | {d["landmark"]} |')
  md.append('')
 md+=['## Editing and verification','','- `tools/map_layouts/authored.py`: all 80 authored compositions, prop palettes and spatial narratives.','- `tools/map_layouts/tidekin.py`: 39 moodboard-led sea-built compositions, coastal furniture and amphibian residents.','- `tools/map_layouts/tower.py`: portrait tower interiors and continuous ascending stair routes.','- `tools/map_layouts/build.py`: native SVG drawing components and detail-sheet construction.','- `tools/map_layouts/overviews.py`: cartographic layouts and exact portal graphs.','- `manifest.json`: platforms, supported climbs, props, inhabitants, portals and source coverage for every map.','','From the repository root:','','```sh','python3 tools/map_layouts/build.py','python3 tools/map_layouts/overviews.py','python3 tools/map_layouts/gallery.py','python3 tools/map_layouts/validate.py','python3 tools/map_layouts/render.py --all','```','','Rendering uses the locally installed Chromium through Playwright; generation and static validation use only Python’s standard library. No rendering-performance claims are made for these design artifacts, and the runtime game was not modified.']
 (OUT/'README.md').write_text('\n'.join(md)+'\n')
 print('Built offline catalogue and complete linked index')
if __name__=='__main__':main()
